import { Wrench, Waves, Home, Layers, Zap, Hammer, Droplets, CheckCircle } from 'lucide-react';

export const services = [
  {
    id: 'construccion-y-reformas',
    title: 'Construcción y Reformas',
    subtitle: 'Transformamos tus espacios, desde cero o renovando lo existente.',
    shortDescription: 'Obra nueva, renovaciones y ampliaciones para todo tipo de construcciones.',
    description: 'Nos especializamos en la ejecución de obras nuevas, reformas integrales y ampliaciones. Nuestro equipo de profesionales gestiona cada proyecto con la máxima dedicación para garantizar resultados que superen tus expectativas, cuidando cada detalle desde la cimentación hasta los acabados finales.',
    icon: <Wrench />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Fconstruccion_reformas.jpg?alt=media&token=411072a3-8e39-4f4d-8843-031d4d88632c',
    imageHint: 'construction site',
    features: [
      'Gestión integral de proyectos de obra nueva.',
      'Reformas completas de viviendas y locales comerciales.',
      'Ampliaciones y redistribución de espacios.',
      'Asesoramiento en materiales y soluciones constructivas.',
    ],
  },
  {
    id: 'piscinas',
    title: 'Construcción de Piscinas',
    subtitle: 'El oasis que siempre has soñado, en tu propio hogar.',
    shortDescription: 'Diseño, construcción y mantenimiento de piscinas para que disfrutes del verano.',
    description: 'Diseñamos y construimos piscinas de obra a medida, adaptadas a tu terreno y a tus sueños. Utilizamos las técnicas más avanzadas y materiales de primera calidad para crear espacios únicos de ocio y relax para ti y tu familia.',
    icon: <Waves />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Freforma_piscina.jpg?alt=media&token=c8621246-a44d-4d00-b909-fa04575c1ddc',
    imageHint: 'swimming pool',
    features: [
      'Diseño personalizado de piscinas.',
      'Construcción con hormigón proyectado (gunitado).',
      'Instalación de sistemas de cloración salina y climatización.',
      'Servicio de mantenimiento y reparación.',
    ],
  },
  {
    id: 'reformas-de-interiores',
    title: 'Reformas de Interiores',
    subtitle: 'Renueva el corazón de tu hogar: baños y cocinas funcionales y de diseño.',
    shortDescription: 'Especialistas en reformas de baños y cocinas, optimizando espacio y estilo.',
    description: 'Somos expertos en la reforma de baños y cocinas, dos de las estancias más importantes del hogar. Optimizamos la distribución para ganar funcionalidad y creamos ambientes modernos y acogedores utilizando materiales de última generación.',
    icon: <Home />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Freforma_interior.jpg?alt=media&token=c11e37d1-d4c0-4583-a071-3827c0e8fa8d',
    imageHint: 'modern kitchen',
    features: [
      'Renovación completa de alicatados y pavimentos.',
      'Instalación de fontanería y electricidad nuevas.',
      'Montaje de mobiliario de cocina y baño a medida.',
      'Instalación de platos de ducha, mamparas y sanitarios.',
    ],
  },
  {
    id: 'paramentos-verticales',
    title: 'Paramentos Verticales',
    subtitle: 'Protegemos y embellecemos tus fachadas y muros.',
    shortDescription: 'Soluciones para fachadas y muros, desde revestimientos hasta aislamientos.',
    description: 'Ofrecemos una amplia gama de soluciones para paramentos verticales, incluyendo la aplicación de morteros monocapa, revocos, y sistemas de aislamiento térmico por el exterior (SATE), mejorando la eficiencia energética y la estética de tu edificio.',
    icon: <Layers />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Freforma_edificio.jpg?alt=media&token=6cb121d7-251f-4c97-b067-65a6d57f529b',
    imageHint: 'building facade',
    features: [
      'Aplicación de revestimientos continuos.',
      'Sistemas de Aislamiento Térmico por el Exterior (SATE).',
      'Reparación y rehabilitación de fachadas.',
      'Pintura exterior e impermeabilización.',
    ],
  },
  {
    id: 'electricidad',
    title: 'Electricidad',
    subtitle: 'Instalaciones eléctricas seguras y eficientes para tu tranquilidad.',
    shortDescription: 'Cableado, iluminación, actualizaciones de paneles e inspecciones de seguridad.',
    description: 'Realizamos todo tipo de instalaciones eléctricas, desde el cableado completo de una vivienda hasta la instalación de nuevos puntos de luz, siempre cumpliendo con la normativa vigente para garantizar la máxima seguridad y eficiencia energética.',
    icon: <Zap />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Freforma_edificio.jpg?alt=media&token=6cb121d7-251f-4c97-b067-65a6d57f529b',
    imageHint: 'electrical work',
    features: [
      'Instalaciones eléctricas completas en obra nueva.',
      'Actualización y reforma de instalaciones antiguas.',
      'Boletines eléctricos y certificaciones.',
      'Instalación de iluminación LED de bajo consumo.',
    ],
  },
  {
    id: 'carpinteria',
    title: 'Carpintería',
    subtitle: 'El toque artesanal que marca la diferencia en tus acabados.',
    shortDescription: 'Más de 5 años de experiencia en trabajos de carpintería a medida.',
    description: 'Ofrecemos servicios de carpintería a medida, tanto de madera como de aluminio o PVC. Fabricamos e instalamos puertas, ventanas, armarios empotrados, parqués y todo tipo de mobiliario para dar un acabado perfecto a tu proyecto.',
    icon: <Hammer />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Freforma_edificio.jpg?alt=media&token=6cb121d7-251f-4c97-b067-65a6d57f529b',
    imageHint: 'wood working',
    features: [
      'Carpintería de madera, aluminio y PVC.',
      'Instalación de puertas de paso y de entrada.',
      'Montaje de suelos de parqué y tarima flotante.',
      'Diseño y fabricación de armarios y vestidores a medida.',
    ],
  },
  {
    id: 'fontaneria',
    title: 'Fontanería Especializada',
    subtitle: 'Soluciones duraderas para el sistema de agua de tu hogar o negocio.',
    shortDescription: 'Servicios completos de fontanería, desde instalaciones hasta reparaciones.',
    description: 'Nuestros fontaneros cualificados se encargan de la instalación y reparación de toda la red de saneamiento y agua potable. Garantizamos un trabajo rápido, limpio y duradero, utilizando materiales de la mejor calidad.',
    icon: <Droplets />,
    image: 'https://firebasestorage.googleapis.com/v0/b/local-digital-eye.firebasestorage.app/o/business%2Fyaku%2Ffontaneria.jpg?alt=media&token=8f625686-044f-4c4b-8eb0-c66f229b6aba',
    imageHint: 'plumbing work',
    features: [
      'Instalación completa de redes de fontanería y desagües.',
      'Reparación de fugas y averías.',
      'Instalación de grifería y sanitarios.',
      'Sistemas de agua caliente sanitaria (termos, calderas).',
    ],
  },
];
